server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Photos
    username: username
    password: password
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

photos:
  folder: 'path to your photos directory, that matches up with photoManifest.csv'